//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMIS.Map.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessApp
    {
        public System.Guid BusinessAppGUID { get; set; }
        public string BusinessAppName { get; set; }
        public string BusinessAppCode { get; set; }
        public string BusinessAppShortCode { get; set; }
        public Nullable<System.Guid> ParentGUID { get; set; }
        public Nullable<byte> IsDisabled { get; set; }
        public string DisabledReason { get; set; }
        public string AppUrl { get; set; }
        public string AppIcon { get; set; }
        public string IconClass { get; set; }
        public string IconClassUrl { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Remark { get; set; }
    }
}
