//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMIS.Map.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid UserGUID { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<System.Guid> OrgGUID { get; set; }
        public string PhotoUrl { get; set; }
        public string OfficePhone { get; set; }
        public string TelPhone { get; set; }
        public string HomePhone { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public Nullable<byte> IsLocked { get; set; }
        public string LockedReason { get; set; }
        public Nullable<byte> IsDisabled { get; set; }
        public string DisabledReason { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public string Remark { get; set; }
    }
}
